ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.5
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    GPU_GPU: True
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 1.25, 0]
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 1.25, 0]
    HFOV: 90
  TURN_ANGLE: 10
  FORWARD_STEP_SIZE: 0.065
TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR', 'HEADING_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: test
  DATA_PATH: "~/habitat-api/data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "~/habitat-api/data/scene_datasets/"
