ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.4
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    GPU_GPU: True
  RGB_SENSOR:
    WIDTH: 512
    HEIGHT: 512
    POSITION: [0, 1.25, 0]
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 512
    HEIGHT: 512
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 1.25, 0]
    HFOV: 90
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'Proportional'
    NOISE_MULTIPLIER: 0.5
  TURN_ANGLE: 10
  FORWARD_STEP_SIZE: 0.25
TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['NOISY_POSE_SENSOR', 'POINTGOAL_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: test
  DATA_PATH: "~/habitat-api/data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "~/habitat-api/data/scene_datasets/"
